micronaut:
  application:
    name: cassius
  security:
    enabled: true
    oauth2:
      enabled: true
      clients:
        auth0:
          client-id:
          client-secret:
    endpoints:
      logout:
        enabled: true
        get-allowed: true

strava:
  challengeVerifyToken:
  clientId:
  clientSecret:
  refreshToken:

gcp:
  bucketName:

endpoints:
  all:
    enabled: false
  health:
    enabled: true

jackson:
  mapper:
    ACCEPT_CASE_INSENSITIVE_ENUMS: true
  bean-introspection-module: true
  serializationInclusion: NON_NULL
  deserialization:
    failOnUnknownProperties: false

logger:
  levels:
    io.github.davidmerrick.strava: DEBUG